minimumReleaseAge: 1440
trustPolicy: no-downgrade

ignoredBuiltDependencies:
  - msw
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma

overrides:
  effect@<3.20.0: ">=3.20.0"
